// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ad933dd2-870d-4f5b-ae6e-96294a97785d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_cKUIMsqul",
    "aws_user_pools_web_client_id": "3k3i7ncfa7j8d24offfcvubitu",
    "oauth": {},
    "aws_user_files_s3_bucket": "amplify-type-s3-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://fqnt7qpc55cvlftwnvbup6inda.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
